name = "bitflip-audio"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [{ pattern = "audio.bitflip.show/*", zone_name = "bitflip.show" }]

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "bitflip-audio"

[[r2_buckets]]
binding = "ANALYTICS_EVENTS"
bucket_name = "bitflip-analytics-events"
